services:
  db:
    image: postgres:16
    container_name: aiemailassistant-db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: aiassistant
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
      - otel-collector
    volumes:
      - .:/app
      - huggingface_cache:/root/.cache/huggingface # Mounts the named volume
      # The path /root/.cache/huggingface is the typical default cache location
      # for Hugging Face libraries when running as the root user inside a container.
      # If you run as a non-root user or configure a different cache path via
      # environment variables (like HF_HOME), you'd adjust the container path accordingly.
  
    environment:
      DATABASE_URL: postgresql+asyncpg://appuser:secret@db:5432/aiassistant

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318"
      - "8888:8888"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
volumes:
  pgdata:
  huggingface_cache: {}