# docker-compose.yml (relevant parts for fastapi service and top-level volumes)
services:
  db:
    image: postgres:16
    container_name: aiemailassistant-db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: aiassistant
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
      - otel-collector
    environment:
      DATABASE_URL: postgresql+asyncpg://appuser:secret@db:5432/aiassistant
      # OPENAI_API_KEY will be loaded from .env file
      # REMOVED: HF_HOME, TRANSFORMERS_CACHE, HF_DATASETS_CACHE
    env_file:
      - .env
    volumes:
      - ./app:/code/app  # Your code mount
      # REMOVED: - model_cache_vol:/app_cache/... (or similar hf cache volume mount)
      - ./alembic:/code/alembic                   # NEW: Mount for Alembic scripts and config
      # If alembic.ini is at the project root and not inside ./alembic:
      - ./alembic.ini:/code/alembic.ini         # NEW: Mount for alembic.ini
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318" # OTLP HTTP receiver
      - "8888:8888" # For Prometheus scraping otel-collector metrics

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    # Optional: Add a volume for Grafana data persistence if needed
    # volumes:
    #   - grafana_data:/var/lib/grafana

volumes:
  pgdata: # For PostgreSQL data
  # REMOVED: model_cache_vol: {} (or similar hf cache volume definition)
  # Optional: Add if you uncommented grafana_data volume
  # grafana_data: {}
