# docker-compose.yml
version: "3.9"

services:
  db:
    image: postgres:16
    container_name: aiemailassistant-db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: aiassistant
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
