# docker-compose.yml
services:
  db:
    image: postgres:16
    container_name: aiemailassistant-db
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: aiassistant
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
      - otel-collector
    environment:
      DATABASE_URL: postgresql+asyncpg://appuser:secret@db:5432/aiassistant
      # Explicitly set HF_HOME for the container.
      # The transformers library will create subdirs like 'hub', 'datasets' under this.
      HF_HOME: /cache_vol/huggingface 
      # OPENAI_API_KEY will be loaded from .env file
    env_file:
      - .env
#    device_requests:
 #     - driver: nvidia
  #      count: 1
   #     capabilities: [gpu]
    volumes:
      - ./app:/code/app                             # Your application code
      - ./alembic:/code/alembic                   # Alembic scripts
      - ./alembic.ini:/code/alembic.ini           # Alembic config
      - hf_cache_data:/cache_vol                  # Mount the named volume to /cache_vol

  # ... other services (otel-collector, prometheus, grafana) remain the same ...
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.99.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./observability/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4318:4318" 
      - "8888:8888" 

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"

volumes:
  pgdata:
  hf_cache_data: {} # Define the named volume for Hugging Face cache
