receivers:
  otlp:
    protocols:
      http:

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: "localhost:8888"
  # Optionally send to Jaeger/Grafana Tempo here

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging]   # Add others as needed
