global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["fastapi:8000"]  # Use your FastAPI host:port

  - job_name: "otel-collector"
    metrics_path: /metrics
    static_configs:
      - targets: ["otel-collector:8888"]
