name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CUDA_VISIBLE_DEVICES: ""
      APP_MOCK_AI: "1"
      DATABASE_URL: "sqlite+aiosqlite:///./test.db"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (CI minimal)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-ci.txt

      - name: Lint
        run: |
          ruff check .

      - name: Run tests
        run: |
          pytest -q

      - name: Docker build
        run: |
          docker build -t aiemailassistant:ci .

